### ISSUE TITLE
apple sillicon version

### ISSUE THREAD

**Issue by vtmocanu** [hedgieinsocks/kubectl-cnf#1]
is it possible to build this also for arm macs?
```
❯ k krew install cnf
Updated the local copy of plugin index.
Installing plugin: cnf
W0802 08:50:15.407087    1395 install.go:164] failed to install plugin "cnf": plugin "cnf" does not offer installation for this platform
failed to install some plugins: [cnf]: plugin "cnf" does not offer installation for this platform
```
thank you for sharing this plugin

**Comment by hedgieinsocks** [comment]
Hi, since it's just a few lines of bash code, I can surely add `darwin` to the krew manifest which will make it installable on macs. The krew team usually approves such things in a few weeks. But just to confirm, you installed it manually and it works as expected, right?

**Comment by vtmocanu** [comment]
Didn't think of it :)
Tried it out and ... it works and it doesn't :)
I don't think it's your fault, i think you can enable darwin.
I think i have a local bug, haven't been able to pin point it yet.
```
find ~/.kube/configs \( -type f -o -type l \) -exec awk '/^current-context:/ {print FILENAME, $2}' {} +\
 | sort -k2 | awk '{print $2}'|fzf
```
this works ok, even tried it in bash
i've hacked the script to:
```
  find "${KCNF_DIR}" \( -type f -o -type l \) -exec awk '/^current-context:/ {print FILENAME, $2}' {} +\
    | sort -k2 \
    | awk '{print $2}' \
    | fzf
  
  exit
```
and it just hangs and does not print anything, if i type something and press enter it works ok, so fzf is working, but does not print anything.
if i remove the `|fzf` the contexts get printed ok, so it's an issue with fzf in my env.

**Comment by vtmocanu** [comment]
Nervermind, i've upgraded fzf and all is good now, you can enable darwin, thanks!

**Comment by hedgieinsocks** [comment]
https://github.com/kubernetes-sigs/krew-index/pull/3998

**Comment by vtmocanu** [comment]
works as expected, thanks @hedgieinsocks !
